[general]
import = [
  "~/.config/alacritty/key_bindings.toml",
  "~/.config/alacritty/themes/github_dark.toml",
]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[debug]
render_timer = false

[env]
# TERM = "alacritty-direct"
TERM = "xterm-256color"

[font]
size = 14

glyph_offset = { x = 0, y = 0 }

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

offset = { x = 0, y = 0 }

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 0.7

dimensions = { columns = 160, lines = 48 }

padding = { x = 6, y = 6 }
