[keyboard]

bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
  { key = "Return", mods = "Shift", chars = "\u001B[13;2u" },
  { key = "Return", mods = "Alt", chars = "\u001B\r" },
]
